name: github_graphql_client
description: Github client using Github API V4 (GraphQL)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  url_launcher: ^5.5.1
  oauth2: ^1.6.1
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true