name: github_graphql_client
description: Github client using Github API V4 (GraphQL)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  url_launcher: ^5.5.1
  oauth2: ^1.6.1
  http: ^0.12.2

  gql: ^0.12.3
  gql_exec: ^0.2.4
  gql_link: ^0.3.0
  gql_http_link: ^0.2.9
  window_to_front:
    path: '../window_to_front'

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  gql_build: ^0.0.11
  pedantic: ^1.9.0

flutter:

  uses-material-design: true